### ISSUE TITLE
bash: unbound var "pkg"

### ISSUE THREAD

**Issue by Patterner** [RhysU/c99sh#25]
1> bash c99sh
c99sh: line 126: pkg: unbound variable

1> bash --version
GNU bash, Version 4.3.30(1)-release (x86_64-pc-linux-gnu) (Debian Jessie)

**Comment by RhysU** [comment]
What happens if you use "declare -A pkg=()" instead of the current line without the =()?

**Comment by Patterner** [comment]
It works now.

1> ./basic/hello 
Hello, world!

**Comment by RhysU** [comment]
Please submit a pull request with that change.

- Rhys
