### ISSUE TITLE
Support dual shebang/compiled behavior

### ISSUE THREAD

**Issue by mcandre** [RhysU/c99sh#28]
Is there another way to write the shebang line `#!/usr/bin/env c99sh`, so that a .c file supports both c99sh invocation, as well as traditional gcc compilation? I think this shebang would be rejected by most C compilers?

**Comment by RhysU** [comment]
gcc definitely dislikes the shebang.  I'm not aware of a way to write the shebang differently that would be accepted.  In particular, I've never seen a pragma starting with !.  Doesn't mean it can't be done, but it would take some serious head scratching.

**Comment by RhysU** [comment]
If you want to just run a .c file, you can do that with 'c99sh foo.c'

**Comment by mcandre** [comment]
Some programming languages without native support for shebang comments can be hacked with polyglot code that is interepreted one way by the shell, and another way by the compiler.

E.g. https://rosettacode.org/wiki/Multiline_shebang#C

Not pretty, but it works

**Comment by RhysU** [comment]
Interesting sample, but notice it emulated a barebones c99sh. The .c file
could not be compiled directly.

**Comment by jtsagata** [comment]
This seems to work
```
#if 0
P=$(basename $0 .c)
c11sh $P
exit
#endif

int main() {
  std::cout << "Hello shell\n";
}
```

**Comment by RhysU** [comment]
What do you mean by "work"?  With those file contents, what collection of things can you do?

1. With execute bit set, run ./foo.cxx?
1. With those file contents in a .cxx file, run g++ foo.cxx (you meant cxxsh, yeah)?

I don't see how the first works given that the shebang looks concerned.

**Comment by jtsagata** [comment]
Yes it must say cxxsh (i have c11sh to use clang and cxxsh to use gcc in my setup).
Both ```chmod +x foo.ccp && ./foo.cpp``` and ```cxxsh foo.cpp``` work in my linux box. The shell ignores the preprocessor directives as comments and run until exit, the compiler ignore the shell code.

I say seems as i have not test it above this demo, so maybe there is edge cases. But it's a working start.

**Comment by RhysU** [comment]
Thanks guys!  I didn't think that bash would accept that shebang.  I updated the README and included a few examples with a somewhat shortened variant of what @jtsagata proposed.

**Comment by jtsagata** [comment]
Thanks for credits. May i suggest a better example; 
```
#if 0
exec cxxsh "$0"
#endif

int foo() {
  return 42;
}

// Add a -D__MAIN__ to cxxrc to make it runnable.
#ifdef __MAIN__
int main() {
  std::cout << "The answer is " << foo() << ".\n";
}
#endif
```
This idea is stolen from python. I does not replace a proper test suite but its nice for some quick testing.

**Comment by RhysU** [comment]
I like it.  I added a -t option to make it a bit simpler, and I highlighted
the idea in the README.

**Comment by jtsagata** [comment]
The ```-t``` flag solution is nice, but have a big issue. Lets say i use ```test()```  as a documentation for the function ```logic()```. The user run the source file and quick test and see examples of function defined in a file. But i don't want that to be in the final executable or library. Please also add a -D__C99SH__ or something in the script compile line.
Thanks and Happy New Year

**Comment by RhysU** [comment]
The static keyword makes symbol test() visible only in the file translation
unit. The linker should effectively drop it from any non-c99sh build.

- Rhys

On Jan 1, 2017 3:04 AM, "jtsagata" <notifications@github.com> wrote:

The -t flag solution is nice, but have a big issue. Lets say i use test()
as a documentation for the function logic(). The user run the source file
and quick test and see examples of function defined in a file. But i don't
want that to be in the final executable or library. Please also add a
-D__C99SH__ or something in the script compile line.
Thanks and Happy New Year

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/RhysU/c99sh/issues/28#issuecomment-269895267>, or mute
the thread

**Comment by RhysU** [comment]
Just confirming what I suggested earlier today using the basic/quicktest.c example:

    $ gcc -O0 -c quicktest.c && strings quicktest.o | grep test
    quicktest.c
    test

    $ gcc -O2 -c quicktest.c && strings quicktest.o | grep test
    quicktest.c

That is, with any reasonable amount of optimization the extra static identifier is dropped from the object file.

(I was a bit sloppy with my translation unit terminology, but the conclusion remains the same).

**Comment by RhysU** [comment]
I'm going to skip on adding an automatic __C99SH__ define as this can be accomplished with the control file in whatever manner you like.  Generally, the less conditional compilation the better.  If you've a define, your regular build system never checks the #ifdef __C99SH__ code compiles.  If you use the -t option, the static test() logic always has to compile even if folks never use c99sh to run it.
